version: '3'

services:
  redis:
    container_name: redis
    image: "redis:latest"
    ports:
      - "6379:6379"
      # 추후 volume 연결
    environment:
      TZ: "Asia/Seoul"

  doomz:
    container_name: doomz
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      TZ: "Asia/Seoul"
      
  mysql:
    container_name: mysql
    image: "mysql:latest"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: doomz             
      TZ: "Asia/Seoul"                   
