version: '3'

services:
  redis:
    container_name: redis
    image: "redis:latest"
    ports:
      - "6379:6379"
# 추후 volume 연결

  spring-app:
    build:
      context: /home/ubuntu/app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis