scrape_configs:
  - job_name: 'spring-actuator'
    metrics_path: '/api/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['be-spring-blue-1:8080', 'be-spring-green-1:8080']
