spring:
  config:
    activate:
      on-profile: dev

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_ID}
            client-secret: ${KAKAO_KEY}
            client-authentication-method: client_secret_post
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-name: Kakao
        #            scope:
        #              - profile_nickname
        #              - account_email
        #              - profile_image
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

      logging:
        level:
          org.hibernate.SQL: debug  #로그로 SQL 남기기

  data:
    redis:
      host: 127.0.0.1
      port: 6379

cloud:
  aws:
    s3:
      bucket: ${AWS_S3_DEV_BUCKET}