server:
  port: 8080
  error:
    include-message: always

spring:
  profiles:
    active: dev

    servlet:
      multipart:
        max-file-size: 5MB
        max-request-size: 5MB

  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 200

cloud:
  aws:
    credentials:
      accessKey: ${AWS_S3_ACCESS_KEY}
      secretKey: ${AWS_S3_SECRET_KEY}
    region:
      static: ${AWS_S3_REGION}