[SERVICE]
    Flush            5
    Daemon           Off
    Log_Level        info
    Parsers_File     parsers.conf

# Docker 컨테이너 로그 수집
[INPUT]
    Name             forward
    Listen           0.0.0.0
    Port             24224

# Spring Blue 서비스 로그 처리
[FILTER]
    Name             parser
    Match            spring.blue
    Key_Name         log
    Parser           spring_json
    Reserve_Data     On

# Spring Green 서비스 로그 처리
[FILTER]
    Name             parser
    Match            spring.green
    Key_Name         log
    Parser           spring_json
    Reserve_Data     On

# Redis 서비스 로그 처리
[FILTER]
    Name             parser
    Match            redis.service
    Key_Name         log
    Parser           redis
    Reserve_Data     On

# CloudWatch로 로그 전송
[OUTPUT]
    Name             cloudwatch_logs
    Match            *
    region           ap-northeast-2
    log_group_name   doomz-spring-app
    log_stream_prefix ${TAG}-
    auto_create_group true