[PARSER]
    Name             spring_json
    Format           json
    Time_Key         timestamp
    Time_Format      %Y-%m-%dT%H:%M:%S.%L
    Time_Keep        On

[PARSER]
    Name             redis
    Format           regex
    Regex            ^(?<time>\d{2}:\d{2}:\d{2}\.\d+) (?<level>\S+) (?<message>.*)$
    Time_Format      %H:%M:%S.%L
    Time_Keep        On